/**
 * Danh mục địa lý tọa độ 34 tỉnh/thành phố và chi tiết các khu vực địa bàn tỉnh Lâm Đồng
 */

export type LocationCoordinate = {
  name: string;
  lat: number;
  lon: number;
  region: "bac_bo" | "trung_bo" | "tay_nguyen" | "nam_bo" | "lam_dong";
  aliases: string[];
};

export const VIETNAM_LOCATIONS: LocationCoordinate[] = [
  // --- TỈNH LÂM ĐỒNG (Chi tiết từng khu vực địa bàn) ---
  {
    name: "Khu vực Đà Lạt (Lâm Đồng)",
    lat: 11.9404,
    lon: 108.4583,
    region: "lam_dong",
    aliases: ["da lat", "đà lạt", "dalat", "tp da lat", "tp đà lạt", "thanh pho da lat", "lam dong", "lâm đồng"],
  },
  {
    name: "Khu vực Bảo Lộc (Lâm Đồng)",
    lat: 11.5458,
    lon: 107.8073,
    region: "lam_dong",
    aliases: ["bao loc", "bảo lộc", "baoloc", "tp bao loc", "tp bảo lộc", "b'lao", "blao"],
  },
  {
    name: "Khu vực Lạc Dương (Lâm Đồng)",
    lat: 12.0225,
    lon: 108.4389,
    region: "lam_dong",
    aliases: ["lac duong", "lạc dương", "langbiang", "lang biang"],
  },
  {
    name: "Khu vực Đức Trọng (Lâm Đồng)",
    lat: 11.7374,
    lon: 108.3756,
    region: "lam_dong",
    aliases: ["duc trong", "đức trọng", "lien nghia", "liên nghĩa", "san bay lien khuong", "sân bay liên khương"],
  },
  {
    name: "Khu vực Đơn Dương (Lâm Đồng)",
    lat: 11.7833,
    lon: 108.5667,
    region: "lam_dong",
    aliases: ["don duong", "đơn dương", "thanh my", "thạnh mỹ", "d'ran", "dran"],
  },
  {
    name: "Khu vực Di Linh (Lâm Đồng)",
    lat: 11.5333,
    lon: 108.0667,
    region: "lam_dong",
    aliases: ["di linh", "dilinh", "djiring"],
  },
  {
    name: "Khu vực Lâm Hà (Lâm Đồng)",
    lat: 11.8333,
    lon: 108.1833,
    region: "lam_dong",
    aliases: ["lam ha", "lâm hà", "dinh van", "đinh văn", "nam ban"],
  },
  {
    name: "Khu vực Bảo Lâm (Lâm Đồng)",
    lat: 11.6333,
    lon: 107.8167,
    region: "lam_dong",
    aliases: ["bao lam", "bảo lâm", "loc thang", "lộc thắng"],
  },
  {
    name: "Khu vực Đạ Huoai (Lâm Đồng)",
    lat: 11.4167,
    lon: 107.5833,
    region: "lam_dong",
    aliases: ["da huoai", "đạ huoai", "dahuoai", "madagui", "ma đa gui"],
  },
  {
    name: "Khu vực Đạ Tẻh (Lâm Đồng)",
    lat: 11.5500,
    lon: 107.5333,
    region: "lam_dong",
    aliases: ["da teh", "đạ tẻh", "dateh"],
  },
  {
    name: "Khu vực Cát Tiên (Lâm Đồng)",
    lat: 11.6000,
    lon: 107.4167,
    region: "lam_dong",
    aliases: ["cat tien", "cát tiên", "cattien", "dong nai thuong"],
  },
  {
    name: "Khu vực Đam Rông (Lâm Đồng)",
    lat: 12.0833,
    lon: 108.1667,
    region: "lam_dong",
    aliases: ["dam rong", "đam rông", "damrong", "bang amang"],
  },

  // --- CÁC TỈNH / THÀNH PHỐ TRỰC THUỘC TRUNG ƯƠNG (34 ĐƠN VỊ CẤP TỈNH) ---
  {
    name: "Thủ đô Hà Nội",
    lat: 21.0285,
    lon: 105.8542,
    region: "bac_bo",
    aliases: ["ha noi", "hà nội", "hanoi", "hn"],
  },
  {
    name: "Thành phố Hồ Chí Minh",
    lat: 10.8231,
    lon: 106.6297,
    region: "nam_bo",
    aliases: ["ho chi minh", "hồ chí minh", "hcm", "tphcm", "tp hcm", "sai gon", "sài gòn"],
  },
  {
    name: "Thành phố Hải Phòng",
    lat: 20.8449,
    lon: 106.6881,
    region: "bac_bo",
    aliases: ["hai phong", "hải phòng", "haiphong", "hp"],
  },
  {
    name: "Thành phố Đà Nẵng",
    lat: 16.0544,
    lon: 108.2022,
    region: "trung_bo",
    aliases: ["da nang", "đà nẵng", "danang", "dn"],
  },
  {
    name: "Thành phố Cần Thơ",
    lat: 10.0452,
    lon: 105.7469,
    region: "nam_bo",
    aliases: ["can tho", "cần thơ", "cantho"],
  },
  {
    name: "Thành phố Huế",
    lat: 16.4637,
    lon: 107.5909,
    region: "trung_bo",
    aliases: ["hue", "huế", "thua thien hue", "thừa thiên huế"],
  },
  {
    name: "Tỉnh Quảng Ninh",
    lat: 21.0064,
    lon: 107.2925,
    region: "bac_bo",
    aliases: ["quang ninh", "quảng ninh", "ha long", "hạ long"],
  },
  {
    name: "Tỉnh Bắc Ninh",
    lat: 21.1861,
    lon: 106.0763,
    region: "bac_bo",
    aliases: ["bac ninh", "bắc ninh", "bacninh"],
  },
  {
    name: "Tỉnh Hải Dương",
    lat: 20.9373,
    lon: 106.3145,
    region: "bac_bo",
    aliases: ["hai duong", "hải dương"],
  },
  {
    name: "Tỉnh Hưng Yên",
    lat: 20.6464,
    lon: 106.0511,
    region: "bac_bo",
    aliases: ["hung yen", "hưng yên"],
  },
  {
    name: "Tỉnh Thái Bình",
    lat: 20.4463,
    lon: 106.3366,
    region: "bac_bo",
    aliases: ["thai binh", "thái bình"],
  },
  {
    name: "Tỉnh Nam Định",
    lat: 20.4344,
    lon: 106.1804,
    region: "bac_bo",
    aliases: ["nam dinh", "nam định"],
  },
  {
    name: "Tỉnh Ninh Bình",
    lat: 20.2506,
    lon: 105.9745,
    region: "bac_bo",
    aliases: ["ninh binh", "ninh bình"],
  },
  {
    name: "Tỉnh Thanh Hóa",
    lat: 19.8067,
    lon: 105.7852,
    region: "trung_bo",
    aliases: ["thanh hoa", "thanh hóa"],
  },
  {
    name: "Tỉnh Nghệ An",
    lat: 18.6734,
    lon: 105.6813,
    region: "trung_bo",
    aliases: ["nghe an", "nghệ an", "vinh"],
  },
  {
    name: "Tỉnh Hà Tĩnh",
    lat: 18.3559,
    lon: 105.9059,
    region: "trung_bo",
    aliases: ["ha tinh", "hà tĩnh"],
  },
  {
    name: "Tỉnh Quảng Bình",
    lat: 17.4690,
    lon: 106.6225,
    region: "trung_bo",
    aliases: ["quang binh", "quảng bình", "dong hoi", "đồng hới"],
  },
  {
    name: "Tỉnh Quảng Trị",
    lat: 16.8167,
    lon: 107.1000,
    region: "trung_bo",
    aliases: ["quang tri", "quảng trị", "dong ha", "đông hà"],
  },
  {
    name: "Tỉnh Quảng Nam",
    lat: 15.5667,
    lon: 108.4833,
    region: "trung_bo",
    aliases: ["quang nam", "quảng nam", "hoi an", "hội an", "tam ky", "tam kỳ"],
  },
  {
    name: "Tỉnh Quảng Ngãi",
    lat: 15.1205,
    lon: 108.7923,
    region: "trung_bo",
    aliases: ["quang ngai", "quảng ngãi"],
  },
  {
    name: "Tỉnh Bình Định",
    lat: 13.7830,
    lon: 109.2197,
    region: "trung_bo",
    aliases: ["binh dinh", "bình định", "quy nhon", "quy nhơn"],
  },
  {
    name: "Tỉnh Phú Yên",
    lat: 13.0882,
    lon: 109.3149,
    region: "trung_bo",
    aliases: ["phu yen", "phú yên", "tuy hoa", "tuy hòa"],
  },
  {
    name: "Tỉnh Khánh Hòa",
    lat: 12.2388,
    lon: 109.1967,
    region: "trung_bo",
    aliases: ["khanh hoa", "khánh hòa", "nha trang", "cam ranh"],
  },
  {
    name: "Tỉnh Ninh Thuận",
    lat: 11.5643,
    lon: 108.9950,
    region: "trung_bo",
    aliases: ["ninh thuan", "ninh thuận", "phan rang"],
  },
  {
    name: "Tỉnh Bình Thuận",
    lat: 10.9288,
    lon: 108.1021,
    region: "trung_bo",
    aliases: ["binh thuan", "bình thuận", "phan thiet", "phan thiết", "mui ne", "mũi né"],
  },
  {
    name: "Tỉnh Đắk Lắk",
    lat: 12.6667,
    lon: 108.0500,
    region: "tay_nguyen",
    aliases: ["dak lak", "đắk lắk", "daklak", "buon ma thuot", "buôn ma thuột"],
  },
  {
    name: "Tỉnh Gia Lai",
    lat: 13.9833,
    lon: 108.0000,
    region: "tay_nguyen",
    aliases: ["gia lai", "gialai", "pleiku"],
  },
  {
    name: "Tỉnh Kon Tum",
    lat: 14.3500,
    lon: 108.0000,
    region: "tay_nguyen",
    aliases: ["kon tum", "kontum", "mang den", "măng đen"],
  },
  {
    name: "Tỉnh Đắk Nông",
    lat: 12.0000,
    lon: 107.6833,
    region: "tay_nguyen",
    aliases: ["dak nong", "đắk nông", "gia nghia", "gia nghĩa"],
  },
  {
    name: "Tỉnh Đồng Nai",
    lat: 10.9574,
    lon: 106.8427,
    region: "nam_bo",
    aliases: ["dong nai", "đồng nai", "bien hoa", "biên hòa"],
  },
  {
    name: "Tỉnh Bình Dương",
    lat: 11.1648,
    lon: 106.6667,
    region: "nam_bo",
    aliases: ["binh duong", "bình dương", "thu dau mot", "thủ dầu một"],
  },
  {
    name: "Tỉnh Bà Rịa - Vũng Tàu",
    lat: 10.3460,
    lon: 107.0843,
    region: "nam_bo",
    aliases: ["vung tau", "vũng tàu", "ba ria", "bà rịa", "ba ria vung tau", "bà rịa vũng tàu"],
  },
  {
    name: "Tỉnh Long An",
    lat: 10.5333,
    lon: 106.4167,
    region: "nam_bo",
    aliases: ["long an", "tan an", "tân an"],
  },
  {
    name: "Tỉnh Tiền Giang",
    lat: 10.3500,
    lon: 106.3500,
    region: "nam_bo",
    aliases: ["tien giang", "tiền giang", "my tho", "mỹ tho"],
  },
  {
    name: "Tỉnh Kiên Giang",
    lat: 10.0167,
    lon: 105.0833,
    region: "nam_bo",
    aliases: ["kien giang", "kiên giang", "phu quoc", "phú quốc", "rach gia", "rạch giá"],
  },
  {
    name: "Tỉnh An Giang",
    lat: 10.3833,
    lon: 105.4167,
    region: "nam_bo",
    aliases: ["an giang", "long xuyen", "long xuyên", "chau doc", "châu đốc"],
  },
];
